spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/Quitomos/HelloWorld.git
          searchPaths: spring-cloud-demo/configs
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
